// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function $$default(props) {
  return React.createElement("ul", undefined, Belt_Array.map(props.todos, (function (todo) {
                    return React.createElement("li", undefined, todo.text);
                  })));
}

function getServerSideProps(_ctx) {
  return Promise.resolve({
              props: {
                todos: [
                  {
                    id: 1,
                    text: "first todo"
                  },
                  {
                    id: 2,
                    text: "second todo"
                  },
                  {
                    id: 3,
                    text: "third todo"
                  }
                ]
              }
            });
}

export {
  $$default ,
  $$default as default,
  getServerSideProps ,
  
}
/* react Not a pure module */
